"""empty message

Revision ID: 19bd5eeb08e6
Revises: 28e31536dc30
Create Date: 2025-01-10 12:26:07.486916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19bd5eeb08e6'
down_revision = '28e31536dc30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Art', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('artist_bio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('artwork_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('medium', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dimensions', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('object_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('period', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Art', schema=None) as batch_op:
        batch_op.drop_column('period')
        batch_op.drop_column('title')
        batch_op.drop_column('object_name')
        batch_op.drop_column('department')
        batch_op.drop_column('dimensions')
        batch_op.drop_column('medium')
        batch_op.drop_column('artwork_date')
        batch_op.drop_column('artist_bio')
        batch_op.drop_column('artist')

    # ### end Alembic commands ###
